name: SSH
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          sudo sed -i 's/#Port 22/Port 443/' /etc/ssh/sshd_config
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          PASSWORD=$(openssl rand -base64 12 | tr -d '=+/' | cut -c1-12)
          echo "root:$PASSWORD" | sudo chpasswd
          sudo systemctl restart ssh
          IP=$(curl -s ifconfig.me)
          echo "IP=$IP" >> $GITHUB_ENV
          echo "PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Show
        run: |
          echo ""
          echo "IP: $IP"
          echo "Port: 443"
          echo "Password: $PASSWORD"
          echo ""
          echo "ssh root@$IP -p 443"

      - name: Keep
        run: sleep 360000
